const dogBreeds = [
  "Airedale Terrier",
  "Akita",
  "Alaskan Malamute",
  "American Bulldog ",
  "American Bully (Standard)",
  "American Eskimo Dog (Miniature)",
  "American Eskimo Dog (Standard)",
  "Am. Staffordshire Terrier",
  "American Pit Bull Terrier",
  "Australian Cattle Dog (Heeler)",
  "Australian Kelpie",
  "Australian Shepherd",
  "Austrialian Terrier",
  "Barbet",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Beauceron",
  "Bedlington Terrier",
  "Belgian Malinois",
  "Belgian Tervuren",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Black and Tan Coonhound",
  "Bloodhound",
  "Bluetick Coonhound",
  "Boerboel",
  "Border Collie",
  "Border Terrier",
  "Boston Terrier",
  "Bouvier des Flandres",
  "Boxer",
  "Boykin Spaniel",
  "Bracco Italiano ",
  "Briard",
  "Brittany",
  "Bull Terrier (Standard)",
  "Bull Terrier (Miniature)",
  "Bulldog",
  "Bullmastiff",
  "Cairn Terrier",
  "Cane Corso",
  "Cardigan Welsh Corgi",
  "Catahoula Leopard Dog",
  "Caucasian Shepherd (Ovcharka)",
  "Cavalier King Charles Spaniel",
  "Chesapeake Bay Retriever",
  "Chihuahua (Long hair)",
  "Chihuahua (Smooth)",
  "Chinese Crested",
  "Chinese Shar-Pei",
  "Chinook",
  "Chow Chow",
  "Clumber Spaniel",
  "Cocker Spaniel (American)",
  "Cocker Spaniel (English)",
  "Collie (Smooth)",
  "Collie (Rough)",
  "Coton De Tulear",
  "Dachshund (smooth)",
  "Dachshund (wire/long haired)",
  "Dalmatian",
  "Doberman Pinscher",
  "Dogo Argentino",
  "Dutch Shepherd",
  "English Setter",
  "English Shepherd",
  "English Springer Spaniel",
  "English Toy Spaniel",
  "English Toy Terrier",
  "Eurasier",
  "Field Spaniel",
  "Finnish Lapphund",
  "Finnish Spitz",
  "Flat Coat Retriever",
  "French Bulldog",
  "German Pinscher",
  "German Shepherd Dog",
  "German Shorthaired Pointer",
  "Giant Schnauzer",
  "Glen of Imaal Terrier",
  "Golden Retriever",
  "Gordon Setter",
  "Great Dane",
  "Great Pyrenees",
  "Greyhound",
  "Harrier",
  "Havanese",
  "Irish Setter",
  "Irish Terrier",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Jack Russel Terrier",
  "Japanese Spitz",
  "Keeshond",
  "Komondor",
  "Kooikerhondje",
  "Kuvasz",
  "Labrador Retriever",
  "Lagotto Romagnolo",
  "Lancashire Heeler",
  "Leonberger",
  "Lhasa Apso",
  "Maltese",
  "Miniature American Shepherd",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Newfoundland",
  "Norfolk Terrier",
  "Norwich Terrier",
  "Nova Scotia Duck Tolling Retriever",
  "Olde English Bulldogge",
  "Old English Sheepdog",
  "Papillon",
  "Parson Russell Terrier",
  "Patterdale Terrier (Smooth or Broken)",
  "Patterdale Terrier (Rough)",
  "Pekingese",
  "Pembroke Welsh Corgi",
  "Pharaoh Hound",
  "Plott",
  "Pointer (English)",
  "Pomeranian",
  "Poodle (Miniature)",
  "Poodle (Standard)",
  "Poodle (Toy)",
  "Portugese Water Dog",
  "Presa Canario",
  "Pug",
  "Puli",
  "Pumi",
  "Rat Terrier",
  "Redbone Coonhound",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Russian Toy",
  "Saluki",
  "Samoyed",
  "Schipperke",
  "Scottish Deerhound",
  "Scottish Terrier",
  "Shetland Sheepdog (Sheltie)",
  "Shiba Inu",
  "Shih Tzu",
  "Shiloh Shepherd",
  "Siberian Husky",
  "Silky Terrier",
  "Smooth Fox Terrier",
  "Soft Coated Wheaten Terrier",
  "Spanish Water Dog",
  "Spinone Italiano",
  "St. Bernard",
  "Staffordshire Bull Terrier",
  "Standard Schnauzer",
  "Swedish Vallhund ",
  "Thai Ridgeback",
  "Tibetan Mastiff",
  "Tibetan Spaniel",
  "Tibetan Terrier",
  "Toy Fox Terrier",
  "Treeing Walker Coonhound",
  "Vizsla",
  "Weimaraner",
  "Welsh Springer Spaniel",
  "West Highland White Terrier",
  "Whippet",
  "White Shepherd ",
  "Wire Fox Terrier",
  "Wirehaired Pointing Griffon",
  "Xoloitzcuintli",
  "Yorkshire Terrier",
];
module.exports = dogBreeds;
